### PR TITLE
Update version number to v0.2.0, goes extension and other minor updates

### LINKED ISSUE #12: Enable schema URL for GOES extension
Once the GOES extension is released, we need to enable the schema URL in stac_extensions (search for `constants.GOES_EXTENSION`).

### PR DESCRIPTION
**Pull request by m-mohr**
Release v0.2.0 and activate the GOES extension (fixes #12 once @gadomski commented on it and we released it)

### CODE REVIEW

**Comment by gadomski** [comment]
I took a look over the GOES extension and opened [one issue](https://github.com/stac-extensions/goes/issues/1), once that's resolved I'd say the extension looks good, though it'd be good to get @pjhartzell's input as well.

**Comment by pjhartzell** [comment]
Some comments (all related to the goes extension):
- Add `Test` as an option for `goes:orbital-slot`?
- Uses kebab-case; is snake_case standard/preferable?
- Is there a branch or repo I'm not seeing? The [json schema](https://github.com/stac-extensions/goes/blob/main/json-schema/schema.json) looks like it is still boilerplate from the template.

**Review by pjhartzell — COMMENTED** [review]
See my comments regarding the GOES Extension.

**Comment by m-mohr** [comment]
> * Add `Test` as an option for `goes:orbital-slot`?

It's a bit weird to add Test as an orbital slot, but yeah it's probably the only option we have? Is it the same for ABI? How is ABI data handled before the drift?

> * Uses kebab-case; is snake_case standard/preferable?

For the values? Doesn't really matter, I think kebab in values is a bit more common but we are free to define that. For keys/property names definitively snake case.

> * Is there a branch or repo I'm not seeing? The [json schema](https://github.com/stac-extensions/goes/blob/main/json-schema/schema.json) looks like it is still boilerplate from the template.

No, I just got feedback from @gadomski yesterday, so I still need to work through the goes extension repo now.

**Comment by pjhartzell** [comment]
>It's a bit weird to add Test as an orbital slot, but yeah it's probably the only option we have? Is it the same for ABI? How is ABI data handled before the drift?

ABI Items do not currently include the orbital slot. And the bbox info is grabbed from the source file (rather than a defined constant value). So the Test slot appears to be handled.

>For the values? Doesn't really matter, I think kebab in values is a bit more common but we are free to define that. For keys/property names definitively snake case.

OK, just curious if there was a recommendation. I looked around and saw instances of both.

>No, I just got feedback from @gadomski yesterday, so I still need to work through the goes extension repo now.

Sounds good. 👍

**Comment by m-mohr** [comment]
I've released the goes extension and applied all necessary updates.
The tests seem to all succeed now, too.
I think we are ready to merge and re-release as v0.2.0. 
Do you want to run additional tests or so a re-review, @pjhartzell ?

**Pull request merged**
